/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.sql.Statement;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    Connect con = new Connect();
    public Dashboard() {
        initComponents();

//        Maximizing the JFrame in the open
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        PatientTableLoad();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnRegPatient = new javax.swing.JButton();
        btnAppoinment = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        btnTrackH = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CenterPanal = new javax.swing.JPanel();
        DashboardPanal = new javax.swing.JPanel();
        DashHead = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        welcomemsg = new javax.swing.JLabel();
        userlbl = new javax.swing.JLabel();
        Dashbody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecentAppoinmntTbl = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        RecentPatientsTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        PatientPnl = new javax.swing.JPanel();
        PatientPnlHeader = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PatientSearch = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        PatientPnlBody = new javax.swing.JPanel();
        PatientImgPnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PatientRegPnl = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatientTbl = new javax.swing.JTable();
        PatientRegBtnPnl = new javax.swing.JPanel();
        PatientRegAddPatientBtn = new javax.swing.JButton();
        PatientRegRemvPatientBtn = new javax.swing.JButton();
        PatientRegEditPatientBtn1 = new javax.swing.JButton();
        DctrPnl = new javax.swing.JPanel();
        ApmntPnl = new javax.swing.JPanel();
        HistoryPanal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        Main.setLayout(new java.awt.BorderLayout());

        SideBar.setBackground(new java.awt.Color(15, 118, 110));
        SideBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(75, 5, 10, 5));
        SideBar.setPreferredSize(new java.awt.Dimension(250, 520));
        SideBar.setLayout(new java.awt.GridLayout(6, 1, 50, 10));

        btnDashboard.setBackground(new java.awt.Color(15, 118, 110));
        btnDashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        SideBar.add(btnDashboard);

        btnRegPatient.setBackground(new java.awt.Color(15, 118, 110));
        btnRegPatient.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnRegPatient.setText("Patients");
        btnRegPatient.setBorder(null);
        btnRegPatient.setBorderPainted(false);
        btnRegPatient.addActionListener(this::btnRegPatientActionPerformed);
        SideBar.add(btnRegPatient);

        btnAppoinment.setBackground(new java.awt.Color(15, 118, 110));
        btnAppoinment.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnAppoinment.setForeground(new java.awt.Color(255, 255, 255));
        btnAppoinment.setText("Appointment");
        btnAppoinment.setBorder(null);
        btnAppoinment.setBorderPainted(false);
        btnAppoinment.addActionListener(this::btnAppoinmentActionPerformed);
        SideBar.add(btnAppoinment);

        btnDoctors.setBackground(new java.awt.Color(15, 118, 110));
        btnDoctors.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnDoctors.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctors.setText("Doctors");
        btnDoctors.setBorder(null);
        btnDoctors.setBorderPainted(false);
        btnDoctors.addActionListener(this::btnDoctorsActionPerformed);
        SideBar.add(btnDoctors);

        btnTrackH.setBackground(new java.awt.Color(15, 118, 110));
        btnTrackH.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnTrackH.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackH.setText("Track History");
        btnTrackH.setBorder(null);
        btnTrackH.setBorderPainted(false);
        btnTrackH.addActionListener(this::btnTrackHActionPerformed);
        SideBar.add(btnTrackH);

        Main.add(SideBar, java.awt.BorderLayout.LINE_START);

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(1280, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 118, 110));
        jLabel1.setText("Niroga Hospital Pvt.Ltd");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        Main.add(Header, java.awt.BorderLayout.PAGE_START);

        CenterPanal.setBackground(new java.awt.Color(241, 245, 249));
        CenterPanal.setLayout(new java.awt.CardLayout());

        DashboardPanal.setBackground(new java.awt.Color(241, 245, 249));
        DashboardPanal.setLayout(new java.awt.BorderLayout());

        DashHead.setBackground(new java.awt.Color(241, 245, 249));
        DashHead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 118, 110)));
        DashHead.setPreferredSize(new java.awt.Dimension(1030, 70));
        DashHead.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 53, 71));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Dashboard");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        DashHead.add(jLabel2);

        welcomemsg.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        welcomemsg.setForeground(new java.awt.Color(42, 53, 71));
        welcomemsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomemsg.setText("Welcome Back ");
        DashHead.add(welcomemsg);

        userlbl.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        userlbl.setForeground(new java.awt.Color(42, 53, 71));
        userlbl.setText("User");
        DashHead.add(userlbl);

        DashboardPanal.add(DashHead, java.awt.BorderLayout.PAGE_START);

        Dashbody.setBackground(new java.awt.Color(241, 245, 249));
        Dashbody.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 60, 40));
        Dashbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RecentAppoinmntTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(RecentAppoinmntTbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 710, 210));

        RecentPatientsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(RecentPatientsTbl);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 710, 210));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 71));
        jLabel3.setText("Recent Appointments");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 250, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 53, 71));
        jLabel4.setText("Recent Added Patients");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 250, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 53, 71));
        jLabel6.setText("Remaining Appointments Today");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 20));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(90, 106, 133));
        jButton3.setText("00");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 120));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(42, 53, 71));
        jLabel7.setText("Active Doctors Today");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 20));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(90, 106, 133));
        jButton7.setText("00");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 120));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(42, 53, 71));
        jLabel10.setText("Total Patients");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 20));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(90, 106, 133));
        jButton8.setText("00");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, 120));

        Dashbody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 500));

        DashboardPanal.add(Dashbody, java.awt.BorderLayout.CENTER);

        CenterPanal.add(DashboardPanal, "card2");

        PatientPnl.setBackground(new java.awt.Color(241, 245, 249));
        PatientPnl.setLayout(new java.awt.BorderLayout());

        PatientPnlHeader.setBackground(new java.awt.Color(241, 245, 249));
        PatientPnlHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 118, 110), 1, true));
        PatientPnlHeader.setToolTipText("");
        PatientPnlHeader.setPreferredSize(new java.awt.Dimension(1030, 70));
        PatientPnlHeader.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(42, 53, 71));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Patients");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        PatientPnlHeader.add(jLabel8);

        PatientSearch.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        PatientSearch.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(90, 106, 133));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 5));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        PatientSearch.add(jTextField1);

        PatientPnlHeader.add(PatientSearch);

        PatientPnl.add(PatientPnlHeader, java.awt.BorderLayout.PAGE_START);

        PatientPnlBody.setBackground(new java.awt.Color(241, 245, 249));
        PatientPnlBody.setLayout(new java.awt.BorderLayout());

        PatientImgPnl.setBackground(new java.awt.Color(234, 242, 241));
        PatientImgPnl.setPreferredSize(new java.awt.Dimension(300, 300));
        PatientImgPnl.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\VTA ICT 05\\Hospital & Clinic Management System\\Designs\\PatientImage.jpg")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 3, 10, 10));
        PatientImgPnl.add(jLabel9);

        PatientPnlBody.add(PatientImgPnl, java.awt.BorderLayout.LINE_START);

        PatientRegPnl.setBackground(new java.awt.Color(232, 246, 243));
        PatientRegPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        PatientRegPnl.setForeground(new java.awt.Color(234, 242, 241));
        PatientRegPnl.setLayout(new javax.swing.BoxLayout(PatientRegPnl, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 30, 1));

        PatientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "P_Id", "Name", "DOB", "Contact", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PatientTbl.setSelectionBackground(new java.awt.Color(16, 182, 117));
        jScrollPane2.setViewportView(PatientTbl);

        PatientRegPnl.add(jScrollPane2);

        PatientRegBtnPnl.setBackground(new java.awt.Color(232, 246, 243));
        PatientRegBtnPnl.setPreferredSize(new java.awt.Dimension(710, 50));
        PatientRegBtnPnl.setLayout(new java.awt.GridLayout(1, 2, 10, 80));

        PatientRegAddPatientBtn.setBackground(new java.awt.Color(16, 185, 129));
        PatientRegAddPatientBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        PatientRegAddPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientRegAddPatientBtn.setText("Add Patient");
        PatientRegAddPatientBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 30, 5, 30));
        PatientRegAddPatientBtn.addActionListener(this::PatientRegAddPatientBtnActionPerformed);
        PatientRegBtnPnl.add(PatientRegAddPatientBtn);

        PatientRegRemvPatientBtn.setBackground(new java.awt.Color(225, 77, 77));
        PatientRegRemvPatientBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        PatientRegRemvPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientRegRemvPatientBtn.setText("Remove Patient");
        PatientRegRemvPatientBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 30));
        PatientRegBtnPnl.add(PatientRegRemvPatientBtn);

        PatientRegEditPatientBtn1.setBackground(new java.awt.Color(230, 126, 34));
        PatientRegEditPatientBtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        PatientRegEditPatientBtn1.setForeground(new java.awt.Color(255, 255, 255));
        PatientRegEditPatientBtn1.setText("Edit Patient");
        PatientRegEditPatientBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 30));
        PatientRegBtnPnl.add(PatientRegEditPatientBtn1);

        PatientRegPnl.add(PatientRegBtnPnl);

        PatientPnlBody.add(PatientRegPnl, java.awt.BorderLayout.CENTER);

        PatientPnl.add(PatientPnlBody, java.awt.BorderLayout.CENTER);

        CenterPanal.add(PatientPnl, "card5");

        DctrPnl.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout DctrPnlLayout = new javax.swing.GroupLayout(DctrPnl);
        DctrPnl.setLayout(DctrPnlLayout);
        DctrPnlLayout.setHorizontalGroup(
            DctrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        DctrPnlLayout.setVerticalGroup(
            DctrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        CenterPanal.add(DctrPnl, "card4");

        ApmntPnl.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout ApmntPnlLayout = new javax.swing.GroupLayout(ApmntPnl);
        ApmntPnl.setLayout(ApmntPnlLayout);
        ApmntPnlLayout.setHorizontalGroup(
            ApmntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        ApmntPnlLayout.setVerticalGroup(
            ApmntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        CenterPanal.add(ApmntPnl, "card4");

        HistoryPanal.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout HistoryPanalLayout = new javax.swing.GroupLayout(HistoryPanal);
        HistoryPanal.setLayout(HistoryPanalLayout);
        HistoryPanalLayout.setHorizontalGroup(
            HistoryPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        HistoryPanalLayout.setVerticalGroup(
            HistoryPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        CenterPanal.add(HistoryPanal, "card4");

        Main.add(CenterPanal, java.awt.BorderLayout.CENTER);

        getContentPane().add(Main, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPatientActionPerformed

        PatientPnl.setVisible(true);
        DashboardPanal.setVisible(false);
        HistoryPanal.setVisible(false);
        ApmntPnl.setVisible(false);
        HistoryPanal.setVisible(false);

    }//GEN-LAST:event_btnRegPatientActionPerformed

    private void btnAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppoinmentActionPerformed
        DashboardPanal.setVisible(false);
        HistoryPanal.setVisible(false);
        PatientPnl.setVisible(false);
        ApmntPnl.setVisible(true);
        DctrPnl.setVisible(false);


    }//GEN-LAST:event_btnAppoinmentActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        DashboardPanal.setVisible(true);
        PatientPnl.setVisible(false);
        HistoryPanal.setVisible(false);
        ApmntPnl.setVisible(false);
        DctrPnl.setVisible(false);


    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        DashboardPanal.setVisible(false);
        PatientPnl.setVisible(false);
        HistoryPanal.setVisible(false);
        ApmntPnl.setVisible(false);
        DctrPnl.setVisible(true);    }//GEN-LAST:event_btnDoctorsActionPerformed

    private void btnTrackHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackHActionPerformed
        DashboardPanal.setVisible(false);
        PatientPnl.setVisible(false);
        HistoryPanal.setVisible(true);
        ApmntPnl.setVisible(false);
        DctrPnl.setVisible(false);
    }//GEN-LAST:event_btnTrackHActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PatientRegAddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRegAddPatientBtnActionPerformed
        // TODO add your handling code here:
        AddPatient add_patient = new AddPatient();
        add_patient.setVisible(true);
        
    }//GEN-LAST:event_PatientRegAddPatientBtnActionPerformed

    public static void main(String args[]) {
        //Flat Laf Loading Code
        System.setProperty("flatlaf.useWindowDecorations", "false");
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(Dashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
        // ----------------------------------------------------------------------------

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ApmntPnl;
    private javax.swing.JPanel CenterPanal;
    private javax.swing.JPanel DashHead;
    private javax.swing.JPanel DashboardPanal;
    private javax.swing.JPanel Dashbody;
    private javax.swing.JPanel DctrPnl;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HistoryPanal;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel PatientImgPnl;
    private javax.swing.JPanel PatientPnl;
    private javax.swing.JPanel PatientPnlBody;
    private javax.swing.JPanel PatientPnlHeader;
    private javax.swing.JButton PatientRegAddPatientBtn;
    private javax.swing.JPanel PatientRegBtnPnl;
    private javax.swing.JButton PatientRegEditPatientBtn1;
    private javax.swing.JPanel PatientRegPnl;
    private javax.swing.JButton PatientRegRemvPatientBtn;
    private javax.swing.JPanel PatientSearch;
    private javax.swing.JTable PatientTbl;
    private javax.swing.JTable RecentAppoinmntTbl;
    private javax.swing.JTable RecentPatientsTbl;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton btnAppoinment;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnRegPatient;
    private javax.swing.JButton btnTrackH;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel userlbl;
    private javax.swing.JLabel welcomemsg;
    // End of variables declaration//GEN-END:variables
    
// Loading All the Tables
    private void PatientTableLoad() {
        try {
            Statement pst = con.getConnection().createStatement();
            ResultSet rs = pst.executeQuery("SELECT * FROM patients");
        } catch (SQLException ex) {
            System.getLogger(Dashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
              
    }
    
}
